apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
    spec:
      containers:
      - image: alexun87/test:latest
        name: react-ui
        ports:
        - containerPort: 3000