apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-server
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  source:
    repoURL: https://github.com/AlexanderUngefug/crossplane-argocd.git
    path: nginx
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true