apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-aws-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  source:
    repoURL: https://github.com/AlexanderUngefug/crossplane-argocd.git
    path: react
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true